# Generated by Django 5.1.5 on 2025-02-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_names', models.CharField(max_length=255)),
                ('featured_artists', models.CharField(max_length=255, null=True)),
                ('record_label', models.CharField(default='Independent', max_length=50)),
                ('language', models.CharField(choices=[], max_length=10)),
                ('is_cover', models.BooleanField(default=False)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('Alternative', 'Alternative'), ('Anime ', 'Anime '), ('Blues', 'Blues'), ('Childrens Music', 'Childrens Music'), ('Classical', 'Classical'), ('Comedy', 'Comedy'), ('Country', 'Country'), ('Dance / EMD', 'Dance / EMD'), ('Disney', 'Disney'), ('Easy Listening', 'Easy Listening'), ('Electronic', 'Electronic'), ('Enka', 'Enka'), ('French Pop', 'French Pop'), ('German Folk', 'German Folk'), ('German Pop', 'German Pop'), ('Fitness & Workout', 'Fitness & Workout'), ('Hip-Hop/Rap', 'Hip-Hop/Rap'), ('Holiday', 'Holiday'), ('Indie Pop', 'Indie Pop'), ('Christian & Gospel', 'Christian & Gospel'), ('Instrumental', 'Instrumental'), ('J-Pop', 'J-Pop'), ('Jazz', 'Jazz'), ('K-Pop', 'K-Pop'), ('Karaoke', 'Karaoke'), ('Kayokyoku', 'Kayokyoku'), ('Latino', 'Latino'), ('New Age', 'New Age'), ('Opera', 'Opera'), ('Pop', 'Pop'), ('R&B/Soul', 'R&B/Soul'), ('Reggae', 'Reggae'), ('Rock', 'Rock'), ('Singer/Songwriter', 'Singer/Songwriter'), ('Soundtrack', 'Soundtrack'), ('Spoken Word ', 'Spoken Word '), ('Tex-Mex / Tejano', 'Tex-Mex / Tejano'), ('Vocal', 'Vocal')], max_length=20)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('main_artwork_colour', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=5)),
                ('BPM', models.PositiveIntegerField()),
                ('main_instruments', models.CharField(max_length=255)),
                ('track_type', models.CharField(choices=[('ALBUM', 'ALBUM'), ('EP', 'EP'), ('LP', 'LP'), ('SINGLE', 'SINGLE')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='data/')),
                ('number_of_streams', models.PositiveIntegerField()),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming_app.songmetadata')),
            ],
        ),
    ]
