# Generated by Django 5.1.5 on 2025-02-10 16:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0002_listener_listenermetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='meta_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streaming_app.listenermetadata'),
        ),
        migrations.AddField(
            model_name='listenermetadata',
            name='total_listening_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 10, 16, 48, 13, 152591, tzinfo=datetime.timezone.utc)),
        ),
    ]
