# Generated by Django 5.1.5 on 2025-02-14 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0003_listener_meta_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenermetadata',
            name='total_listening_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 14, 20, 26, 52, 407775, tzinfo=datetime.timezone.utc)),
        ),
    ]
