# Generated by Django 5.1.5 on 2025-02-18 11:21

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streaming_app", "0003_listener_meta_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ArtistMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_songs", models.PositiveIntegerField(default=0)),
                (
                    "genres",
                    models.CharField(
                        choices=[
                            ("Alternative", "Alternative"),
                            ("Anime ", "Anime "),
                            ("Blues", "Blues"),
                            ("Childrens Music", "Childrens Music"),
                            ("Classical", "Classical"),
                            ("Comedy", "Comedy"),
                            ("Country", "Country"),
                            ("Dance / EMD", "Dance / EMD"),
                            ("Disney", "Disney"),
                            ("Easy Listening", "Easy Listening"),
                            ("Electronic", "Electronic"),
                            ("Enka", "Enka"),
                            ("French Pop", "French Pop"),
                            ("German Folk", "German Folk"),
                            ("German Pop", "German Pop"),
                            ("Fitness & Workout", "Fitness & Workout"),
                            ("Hip-Hop/Rap", "Hip-Hop/Rap"),
                            ("Holiday", "Holiday"),
                            ("Indie Pop", "Indie Pop"),
                            ("Christian & Gospel", "Christian & Gospel"),
                            ("Instrumental", "Instrumental"),
                            ("J-Pop", "J-Pop"),
                            ("Jazz", "Jazz"),
                            ("K-Pop", "K-Pop"),
                            ("Karaoke", "Karaoke"),
                            ("Kayokyoku", "Kayokyoku"),
                            ("Latino", "Latino"),
                            ("New Age", "New Age"),
                            ("Opera", "Opera"),
                            ("Pop", "Pop"),
                            ("R&B/Soul", "R&B/Soul"),
                            ("Reggae", "Reggae"),
                            ("Rock", "Rock"),
                            ("Singer/Songwriter", "Singer/Songwriter"),
                            ("Soundtrack", "Soundtrack"),
                            ("Spoken Word ", "Spoken Word "),
                            ("Tex-Mex / Tejano", "Tex-Mex / Tejano"),
                            ("Vocal", "Vocal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="songmetadata",
            name="artist_names",
        ),
        migrations.AlterField(
            model_name="listenermetadata",
            name="total_listening_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 2, 18, 11, 21, 3, 627436, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="songmetadata",
            name="artists",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming_app.artist",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="artist_meta_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="streaming_app.artistmetadata",
            ),
        ),
    ]
