# Generated by Django 5.1.5 on 2025-02-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0004_artist_artistmetadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songmetadata',
            name='BPM',
        ),
        migrations.RemoveField(
            model_name='songmetadata',
            name='featured_artists',
        ),
        migrations.AddField(
            model_name='songmetadata',
            name='spotify_ref',
            field=models.CharField(default=1, max_length=32),
        ),
        migrations.AlterField(
            model_name='listenermetadata',
            name='total_listening_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 24, 10, 48, 47, 928462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='songmetadata',
            name='main_artwork_colour',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='songmetadata',
            name='main_instruments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
