# Generated by Django 5.1.5 on 2025-03-20 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0005_remove_songmetadata_bpm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmetadata',
            name='number_of_songs',
        ),
        migrations.AddField(
            model_name='artistmetadata',
            name='artist_key',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='listenermetadata',
            name='total_listening_time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 20, 11, 23, 18, 169622, tzinfo=datetime.timezone.utc)),
        ),
    ]
