# Generated by Django 5.1.5 on 2025-03-20 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0006_remove_artistmetadata_number_of_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmetadata',
            name='country',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='artistmetadata',
            name='genres',
            field=models.CharField(choices=[('None', 'None'), ('Alternative', 'Alternative'), ('Anime ', 'Anime '), ('Blues', 'Blues'), ('Childrens Music', 'Childrens Music'), ('Classical', 'Classical'), ('Comedy', 'Comedy'), ('Country', 'Country'), ('Dance / EMD', 'Dance / EMD'), ('Disney', 'Disney'), ('Easy Listening', 'Easy Listening'), ('Electronic', 'Electronic'), ('Enka', 'Enka'), ('French Pop', 'French Pop'), ('German Folk', 'German Folk'), ('German Pop', 'German Pop'), ('Fitness & Workout', 'Fitness & Workout'), ('Hip-Hop/Rap', 'Hip-Hop/Rap'), ('Holiday', 'Holiday'), ('Indie Pop', 'Indie Pop'), ('Christian & Gospel', 'Christian & Gospel'), ('Instrumental', 'Instrumental'), ('J-Pop', 'J-Pop'), ('Jazz', 'Jazz'), ('K-Pop', 'K-Pop'), ('Karaoke', 'Karaoke'), ('Kayokyoku', 'Kayokyoku'), ('Latino', 'Latino'), ('New Age', 'New Age'), ('Opera', 'Opera'), ('Pop', 'Pop'), ('R&B/Soul', 'R&B/Soul'), ('Reggae', 'Reggae'), ('Rock', 'Rock'), ('Singer/Songwriter', 'Singer/Songwriter'), ('Soundtrack', 'Soundtrack'), ('Spoken Word ', 'Spoken Word '), ('Tex-Mex / Tejano', 'Tex-Mex / Tejano'), ('Vocal', 'Vocal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listenermetadata',
            name='total_listening_time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 20, 12, 8, 36, 827412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='songmetadata',
            name='genre',
            field=models.CharField(choices=[('None', 'None'), ('Alternative', 'Alternative'), ('Anime ', 'Anime '), ('Blues', 'Blues'), ('Childrens Music', 'Childrens Music'), ('Classical', 'Classical'), ('Comedy', 'Comedy'), ('Country', 'Country'), ('Dance / EMD', 'Dance / EMD'), ('Disney', 'Disney'), ('Easy Listening', 'Easy Listening'), ('Electronic', 'Electronic'), ('Enka', 'Enka'), ('French Pop', 'French Pop'), ('German Folk', 'German Folk'), ('German Pop', 'German Pop'), ('Fitness & Workout', 'Fitness & Workout'), ('Hip-Hop/Rap', 'Hip-Hop/Rap'), ('Holiday', 'Holiday'), ('Indie Pop', 'Indie Pop'), ('Christian & Gospel', 'Christian & Gospel'), ('Instrumental', 'Instrumental'), ('J-Pop', 'J-Pop'), ('Jazz', 'Jazz'), ('K-Pop', 'K-Pop'), ('Karaoke', 'Karaoke'), ('Kayokyoku', 'Kayokyoku'), ('Latino', 'Latino'), ('New Age', 'New Age'), ('Opera', 'Opera'), ('Pop', 'Pop'), ('R&B/Soul', 'R&B/Soul'), ('Reggae', 'Reggae'), ('Rock', 'Rock'), ('Singer/Songwriter', 'Singer/Songwriter'), ('Soundtrack', 'Soundtrack'), ('Spoken Word ', 'Spoken Word '), ('Tex-Mex / Tejano', 'Tex-Mex / Tejano'), ('Vocal', 'Vocal')], max_length=20),
        ),
    ]
