# Generated by Django 5.1.5 on 2025-03-21 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0007_alter_artistmetadata_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmetadata',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listenermetadata',
            name='total_listening_time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 21, 12, 48, 15, 636614, tzinfo=datetime.timezone.utc)),
        ),
    ]
